#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 03 20:20:59 MST 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim gru_tb_behav -key {Behavioral:sim_1:Functional:gru_tb} -tclbatch gru_tb.tcl -log simulate.log"
xsim gru_tb_behav -key {Behavioral:sim_1:Functional:gru_tb} -tclbatch gru_tb.tcl -log simulate.log

